# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: IDEAS Productivity
email: IDEASProductivity@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ideas-productivity.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  ideas-productivity

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-pluralize
  - jekyll-redirect-from
#  - flexible_include # We do use this, but it is not a gem

# This is needed to generate output for future events
future: true

collections:
  events:
    output: true
    permalink: /events/:slug
  events-draft:
    output: true
    permalink: /events-draft/:slug
  series:
    output: true
    permalink: /series/:slug
  impact:
    output: true
    permalink: /impact/:slug

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "events-draft"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "series"
    values:
      layout: "page"

feed:
  collections:
    - events
  excerpt_only: true


search_provider: algolia
algolia:
  application_id: "2U5U5F24YD"
  index_name: dev_ideas
  search_only_api_key: "0075d949e24bc994484f4252d8fec7ea"
  files_to_exclude:
    - _pages/cookies.md
    - _pages/privacy.md


# Site configuration for the Jekyll 3 Pagination Gem
# gems:
#   - jekyll-paginate-v2 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - README.md

# For use with event artifacts (and perhaps elsewhere) 
# Base URLs
doi-resolver-url: https://doi.org
github-url: https://github.com
bsswt-url: https://bssw-tutorial.github.io

# Base URLs for watching and embedding YouTube videos and playlists
youtube-watch-url: https://www.youtube.com/watch?v=
youtube-playlist-url: https://youtube.com/playlist?list=
youtube-embed-v-url: https://www.youtube.com/embed/
youtube-embed-pl-url: https://www.youtube.com/embed/videoseries?list=