# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: IDEAS Productivity
email: IDEASProductivity@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Advancing scientific productivity through better scientific software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ideas-productivity.org" # the base hostname & protocol for your site, e.g. http://example.com
production_url: "https://ideas-productivity.org" # This will not change when the site is built locally
#twitter_username: jekyllrb
github_username:  ideas-productivity

# Build settings
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-pluralize
  - jekyll-redirect-from
  - jekyll_basename_dirname
  - flexible_include

# This is needed to generate output for future events
future: true

collections:
  events:
    output: true
    permalink: /events/:slug
  events-draft:
    output: true
    permalink: /internal/events-draft/:slug
  events-hpcbp:
    output: false
    permalink: /internal/events-hpcbp/:slug
  events-hpcbp-bsswio:
    output: true
    permalink: /internal/events-hpcbp-bsswio/:slug
  events-hpcbp-bsswio-digest:
    output: true
    permalink: /internal/events-hpcbp-bsswio-digest/:slug
  events-hpcbp-mailchimp-announcement:
    output: true
    permalink: /internal/events-hpcbp-mailchimp-announcement/:slug
  events-hpcbp-intro-slides:
    output: true
    permalink: /internal/events-hpcbp-intro-slides/:slug
  events-hpcbp-youtube:
    output: true
    permalink: /internal/events-hpcbp-youtube/:slug
  events-hpcbp-mailchimp-followup:
    output: true
    permalink: /internal/events-hpcbp-mailchimp-followup/:slug
  impact:
    output: true
    permalink: /impact/:slug

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "events-draft"
    values:
      layout: "event"
      sitemap: false
  - scope:
      path: ""
      type: "events-hpcbp"
    values:
      layout: "event"
      sitemap: false
  - scope:
      path: ""
      type: "events-hpcbp-bsswio"
    values:
      layout: bsswio-event
      sitemap: false
  - scope:
      path: ""
      type: "events-hpcbp-bsswio-digest"
    values:
      layout: bsswio-event-digest
      sitemap: false
  - scope:
      path: ""
      type: "events-hpcbp-mailchimp-announcement"
    values:
      layout: hpcbp-mailchimp-announcement
      sitemap: false
  - scope:
      path: ""
      type: "events-hpcbp-intro-slides"
    values:
      layout: hpcbp-intro-slide
      sitemap: false
  - scope:
      path: ""
      type: "events-hpcbp-youtube"
    values:
      layout: hpcbp-youtube
      sitemap: false
  - scope:
      path: ""
      type: "events-hpcbp-mailchimp-followup"
    values:
      layout: hpcbp-mailchimp-followup
      sitemap: false
  - scope:
      path: "internal"
    values:
      sitemap: false
  - scope:
      path: "internal/**"
    values:
      sitemap: false

feed:
  collections:
    - events
  excerpt_only: true


search_provider: algolia
algolia:
  application_id: "2U5U5F24YD"
  index_name: dev_ideas
  search_only_api_key: "5f84ff238bbe1b105add259330b70136"
  files_to_exclude:
    - _pages/cookies.md
    - _pages/privacy.md
    - internal/*
    - internal/index.md
    - internal/hccbp-webinars/*
    - internal/hccbp-webinars/index.md
    - _events-draft/*
    - _events-hpcbp/*
    - _events-hpcbp-bsswio/*
    - _events-hpcbp-bsswio-digest/*
    - _events-hpcbp-mailchimp-announcement/*
    - _events-hpcbp-youtube/*
    - _events-hpcbp-mailchimp-followup/*

# Site configuration for the Jekyll 3 Pagination Gem 
# gems: 
#   - jekyll-paginate-v2 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - README.md
  - vendor

# We have multiple pages where we need to refer to the canonical location
# for the HPC-BP webinar series and also to the directory where the actual events
# are output
hpcbp-series-path: /resources/series/hpc-best-practices-webinars/
hpcbp-events-path: /events

# For use with event artifacts (and perhaps elsewhere) 
# Base URLs
doi-resolver-url: https://doi.org
github-url: https://github.com
bsswt-url: https://bssw-tutorial.github.io

# Base URLs for watching and embedding YouTube videos and playlists
youtube-watch-url: https://www.youtube.com/watch?v=
youtube-playlist-url: https://youtube.com/playlist?list=
youtube-embed-v-url: https://www.youtube.com/embed/
youtube-embed-pl-url: https://www.youtube.com/embed/videoseries?list=

# Limits to check for YouTube uploads
youtube-title-max: 100