toc:
  - title: overview
    slug: overview
    url: /overview/
    subfolderitems:
      - page: Background
        url: /overview/background.html
      - page: Approach
        url: /overview/approach.html
      - page: Impact
        url: /overview/impact.html
  - title: activities
    slug: activities
    url: /activities/
    subfolderitems:
      - page: IDEAS-ECP
        url: /activities/ideas-ecp/
      - page: IDEAS-Watersheds
        url: /activities/ideas-watersheds/
      - page: xSDK
        url: /activities/xsdk/
      - page: BSSw Fellowship
        url: /activities/bsswf/
      - page: BSSw.io
        url: /activities/bsswio/
      - page: IDEAS-Classic
        url: /activities/ideas-classic/
  - title: resources
    slug: resources
    url: /resources/
    subfolderitems:
      - page: Events
        url: /resources/events/
      - page: Events by Series
        url: /resources/series/
      - page: Tools and Practices
        url: /resources/tools-and-practices.html
  - title: join the community!
    slug: join
    url: /join.html