name: Check website links

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for broken links
        id: link-report
        uses: elliotforbes/broken-link-checker@1.0.2
        with:
          url: "https://ideas-productivity.github.io/"
          cmd_params: "--buffer-size=8192 --max-connections=10 --color=always --verbose"
