name: Check URLs in Changed Files

on: [pull_request, push, workflow_dispatch]

jobs:  
  urlchecks:
    name: check-urls
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
    
    - id: files
#      uses: jitterbit/get-changed-files@v1 ### Hasn't been updated to Node16
      uses: masesgroup/retrieve-changed-files@v3
      with:
        format: 'csv'

    # We maintain the lists of the URLs and URL patterns excluded from checking in separate files so that we can use
    # it in multiple workflows, while easily maintaining consistency.
    - name: Read exclude-urls list
      id: ex-urls
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/exclude-urls.txt
#
    - name: Read exclude-urls list
      id: ex-patterns
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.github/workflows/exclude-patterns.txt

    - name: urls-checker
      uses: urlstechie/urlchecker-action@0.0.34
      with:
        # Use common exclude list read in above
        exclude_urls: ${{ steps.ex-urls.outputs.content }}
        exclude_patterns: ${{ steps.ex-patterns.outputs.content }}
        timeout: 10
        retry_count: 3
        print_all: false
